### ISSUE TITLE
Returning only the fields you want

### ISSUE THREAD

**Issue by reneklacan** [ruby-grape/grape-entity#190]
Hello!

I was trying to use this feature with nested data, something similar to example from README:

```
data = Entity.represent(model, only: [:title, { user: [:name, :email] }])
```

But it is actually returning all fields from `user`, not just `name` and `email`

I am using `grape-entity` version `0.4.8`

**Comment by dblock** [comment]
This _may_ have been fixed on HEAD, would you please give it a try with `github: 'ruby-grape/grape-entity'`?

**Comment by reneklacan** [comment]
I just tried and it has different behaviour, it's returning empty hash (`user: {}`) for me now. And I am sure that fields are present there (tried both string and symbols)

**Comment by dblock** [comment]
Let us know what you find and whether you need any help. There're a bunch of specs [here](https://github.com/ruby-grape/grape-entity/blob/2baf103f5a0574a4d83a7453b2fbeec998a6a46d/spec/grape_entity/entity_spec.rb#L633), I would try to extend those first to replicate the behavior you have.

**Comment by chrisyoumans** [comment]
I'm experiencing the same thing. For @reneklacan's example, I found that putting `user` into an array seems to solve whatever the issue is. Obviously that's not really a solution and I'm not entirely sure why that corrects it, but it does.

It looks like this started happening in 0.4.8. 0.4.5 does not perform this way.

When I get a bit more time I'll try to dig in more, unless someone else happens to know what's going on and a fix just hasn't made it in yet. :)

**Comment by dmitry** [comment]
`only` in 0.4.8 works for me without any issues, it loads nested records the same as root attributes.

**Comment by reneklacan** [comment]
Looks like this is already working so I'm going to close this issue, Thank you!
