### ISSUE TITLE
:if conditional expression isn't validating my ruby object correctly

### ISSUE THREAD

**Issue by dnguyenchevy** [ruby-grape/grape-entity#306]
ruby - 2.5.1
grape-entity - 0.7.1

For some reason when I express `if:` condition within my entity based on another attribute, it doesn't seem to be exposing the attribute as I expected. Am I understanding this correctly?

Example I mocked out

```ruby
class User < Grape::Entity
  with_options(expose_nil: false) do
    expose :name, if: { role: 'USER' }
    expose :role
  end
end

# mocking ruby object model
user = SimpleDelegator.new(name: 'Bob', role: 'USER')

entity = User.new(user)

entity.to_json
#=> { "role": "USER" }
```

I was expecting the following response
```ruby
entity.to_json
{ "name": "Bob", "role": "USER" }
```

I was debugging through this, and it appears that this expression [here](https://github.com/ruby-grape/grape-entity/blob/master/lib/grape_entity/condition/hash_condition.rb#L18) in the `HashCondition` class always expresses false.

**Comment by al** [comment]
I think that's expected behaviour.

From my reading, hash conditions operate on the options not the entity/underlying model as you are expecting. The example from the README:

```ruby
expose :ip, if: { type: :full } # exposed if options :type has a value of :full
```

(keyword _options_). That interpretation is supported by the line of code that you referenced.

To achieve the effect you expect I think you'll need to use a Proc, e.g.

```ruby
expose :name, if: ->(object, _options) { object.role == 'USER' }
```

**Comment by dnguyenchevy** [comment]
Ahhh, that makes sense. 

Thanks for clarity.
